name: Master Branch Push

on:
  push:
    branches: [ master, v4 ] # TODO: Remove v4 before committing.

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
#  gradle-build:
#    runs-on: ubuntu-latest
#    name: Gradle Build
#    steps:
#      - name: Checkout Code
#        uses: actions/checkout@v5
#
#      - name: Set Up JDK 21
#        uses: actions/setup-java@v5
#        with:
#          distribution: 'temurin'
#          java-version: '21'
#
#      - name: Setup Gradle
#        uses: gradle/actions/setup-gradle@v5
#
#      - name: Build with Gradle
#        run: gradle shadowJar
#
#  gradle-test:
#    runs-on: ubuntu-latest
#    name: Gradle (${{ matrix.gradle-version }}) Test
#    strategy:
#      fail-fast: false
#      matrix:
#        gradle-version: [8.14.3, 9.2.1]
#    steps:
#      - name: Checkout Code
#        uses: actions/checkout@v5
#
#      - name: Set Up JDK 21
#        uses: actions/setup-java@v5
#        with:
#          distribution: 'temurin'
#          java-version: '21'
#
#      - name: Setup Gradle ${{ matrix.gradle-version }}
#        uses: gradle/actions/setup-gradle@v5
#        with:
#          gradle-version: '${{ matrix.gradle-version}}'
#
#      - name: Login to Docker Hub
#        uses: docker/login-action@v3
#        with:
#          registry: ${{ secrets.FORGEJO_REGISTRY }}
#          username: ${{ secrets.FORGEJO_USERNAME }}
#          password: ${{ secrets.FORGEJO_TOKEN }}
#
#      - name: Start Docker Compose for Tests
#        run: docker compose -f docker-compose.test.yml up -d --wait
#
#      - name: Test with Gradle
#        run: gradle test
#        env:
#          CAFEBOT_API_URL: 'http://localhost:5000'
#
#      - name: Tear Down Docker Compose
#        run: docker compose -f docker-compose.test.yml down -v
#
#  docker-release:
#    if: ${{ !startsWith(github.head_ref, 'dependabot/') }}
#    name: Docker PR Release
#    runs-on: ubuntu-latest
#    needs: [ gradle-build, gradle-test ]
#    steps:
#      -
#        name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v3
#      -
#        name: Checkout Repository
#        uses: actions/checkout@v5
#      -
#        name: Login to Docker Hub
#        uses: docker/login-action@v3
#        with:
#          registry: ${{ secrets.FORGEJO_REGISTRY }}
#          username: ${{ secrets.FORGEJO_USERNAME }}
#          password: ${{ secrets.FORGEJO_TOKEN }}
#      -
#        name: Build and Push to Custom Registry
#        uses: docker/build-push-action@v6
#        with:
#          push: true
#          tags: |
#            ${{ secrets.FORGEJO_REGISTRY }}/${{ secrets.FORGEJO_USERNAME }}/cafebot-bot:unstable
#            ${{ secrets.FORGEJO_REGISTRY }}/${{ secrets.FORGEJO_USERNAME }}/cafebot-bot:pr-${{ github.event.pull_request.number }}
#          provenance: true
#          sbom: true

  release-please:
    name: Update Changelog
    runs-on: ubuntu-latest
#    needs: [ gradle-build, gradle-test ]
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      -
        name: Update Version Number and Release to GitHub
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.PERSONAL_PAT }}
          manifest-file: .github/.release-please-manifest.json
          config-file: .github/.release-please-config.json
